/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Merchant Search API
 * Search for merchant identification data using the acquirer provide name and card acceptor identifiers
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.merchant_search_api.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SearchAttrList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:06.818+05:30[Asia/Kolkata]")
public class SearchAttrList {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantCity")
  private String merchantCity = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantStreetAddress")
  private String merchantStreetAddress = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantName")
  private String merchantName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantState")
  private String merchantState = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaMerchantId")
  private Double visaMerchantId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("acquiringBin")
  private Integer acquiringBin = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantUrl")
  private String merchantUrl = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantPhoneNumber")
  private Double merchantPhoneNumber = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("acquirerCardAcceptorId")
  private String acquirerCardAcceptorId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantCountryCode")
  private Integer merchantCountryCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantPostalCode")
  private String merchantPostalCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaStoreId")
  private Double visaStoreId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("businessRegistrationId")
  private String businessRegistrationId = null;
  
  public SearchAttrList merchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
    return this;
  }

  
  /**
  * City of the registered Merchant
  * @return merchantCity
  **/
  @ApiModelProperty(required = true, value = "City of the registered Merchant")
  public String getMerchantCity() {
    return merchantCity;
  }
  public void setMerchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
  }
  
  public SearchAttrList merchantStreetAddress(String merchantStreetAddress) {
    this.merchantStreetAddress = merchantStreetAddress;
    return this;
  }

  
  /**
  * Address of the registered Merchant
  * @return merchantStreetAddress
  **/
  @ApiModelProperty(required = true, value = "Address of the registered Merchant")
  public String getMerchantStreetAddress() {
    return merchantStreetAddress;
  }
  public void setMerchantStreetAddress(String merchantStreetAddress) {
    this.merchantStreetAddress = merchantStreetAddress;
  }
  
  public SearchAttrList merchantName(String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

  
  /**
  * Name of the Merchant or Supplier. Note: Optional when any one of VisaMerchantId or VisaStoreId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.
  * @return merchantName
  **/
  @ApiModelProperty(required = true, value = "Name of the Merchant or Supplier. Note: Optional when any one of VisaMerchantId or VisaStoreId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.")
  public String getMerchantName() {
    return merchantName;
  }
  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }
  
  public SearchAttrList merchantState(String merchantState) {
    this.merchantState = merchantState;
    return this;
  }

  
  /**
  * State of the registered Merchant. Ex: US
  * @return merchantState
  **/
  @ApiModelProperty(required = true, value = "State of the registered Merchant. Ex: US")
  public String getMerchantState() {
    return merchantState;
  }
  public void setMerchantState(String merchantState) {
    this.merchantState = merchantState;
  }
  
  public SearchAttrList visaMerchantId(Double visaMerchantId) {
    this.visaMerchantId = visaMerchantId;
    return this;
  }

  
  /**
  * Unique identifier for Merchant provided by VISA. Note: Optional when any one of MerchantName or VisaStoreId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.
  * @return visaMerchantId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier for Merchant provided by VISA. Note: Optional when any one of MerchantName or VisaStoreId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.")
  public Double getVisaMerchantId() {
    return visaMerchantId;
  }
  public void setVisaMerchantId(Double visaMerchantId) {
    this.visaMerchantId = visaMerchantId;
  }
  
  public SearchAttrList acquiringBin(Integer acquiringBin) {
    this.acquiringBin = acquiringBin;
    return this;
  }

  
  /**
  * Acquirer Bin number. Required when AcquirerCardAcceptorId is provided
  * @return acquiringBin
  **/
  @ApiModelProperty(required = true, value = "Acquirer Bin number. Required when AcquirerCardAcceptorId is provided")
  public Integer getAcquiringBin() {
    return acquiringBin;
  }
  public void setAcquiringBin(Integer acquiringBin) {
    this.acquiringBin = acquiringBin;
  }
  
  public SearchAttrList merchantUrl(String merchantUrl) {
    this.merchantUrl = merchantUrl;
    return this;
  }

  
  /**
  * URL of the registered Merchant which provides information about the Merchant. Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or BusinessRegistrationId or AcquirerCardAcceptorId is provided.
  * @return merchantUrl
  **/
  @ApiModelProperty(required = true, value = "URL of the registered Merchant which provides information about the Merchant. Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or BusinessRegistrationId or AcquirerCardAcceptorId is provided.")
  public String getMerchantUrl() {
    return merchantUrl;
  }
  public void setMerchantUrl(String merchantUrl) {
    this.merchantUrl = merchantUrl;
  }
  
  public SearchAttrList merchantPhoneNumber(Double merchantPhoneNumber) {
    this.merchantPhoneNumber = merchantPhoneNumber;
    return this;
  }

  
  /**
  * Phone number of the registered Merchant. MerchantPhoneNumber is optional field with VisaMerchantId, VisaStoreId, BusinessRegistrationId, MerchantUrl, MerchantName, AcquirerCardAcceptorId. Useful in narrowing down the results
  * @return merchantPhoneNumber
  **/
  @ApiModelProperty(required = true, value = "Phone number of the registered Merchant. MerchantPhoneNumber is optional field with VisaMerchantId, VisaStoreId, BusinessRegistrationId, MerchantUrl, MerchantName, AcquirerCardAcceptorId. Useful in narrowing down the results")
  public Double getMerchantPhoneNumber() {
    return merchantPhoneNumber;
  }
  public void setMerchantPhoneNumber(Double merchantPhoneNumber) {
    this.merchantPhoneNumber = merchantPhoneNumber;
  }
  
  public SearchAttrList acquirerCardAcceptorId(String acquirerCardAcceptorId) {
    this.acquirerCardAcceptorId = acquirerCardAcceptorId;
    return this;
  }

  
  /**
  * Acquirer Card Acceptor Id. Pre append ‘0’ if the data is not 15 digit. Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or BusinessRegistrationId or MerchantUrl is provided.
  * @return acquirerCardAcceptorId
  **/
  @ApiModelProperty(required = true, value = "Acquirer Card Acceptor Id. Pre append ‘0’ if the data is not 15 digit. Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or BusinessRegistrationId or MerchantUrl is provided.")
  public String getAcquirerCardAcceptorId() {
    return acquirerCardAcceptorId;
  }
  public void setAcquirerCardAcceptorId(String acquirerCardAcceptorId) {
    this.acquirerCardAcceptorId = acquirerCardAcceptorId;
  }
  
  public SearchAttrList merchantCountryCode(Integer merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
    return this;
  }

  
  /**
  * Country Code of the registered Merchant.Merchant Country code is mandatory with MerchantName
  * @return merchantCountryCode
  **/
  @ApiModelProperty(required = true, value = "Country Code of the registered Merchant.Merchant Country code is mandatory with MerchantName")
  public Integer getMerchantCountryCode() {
    return merchantCountryCode;
  }
  public void setMerchantCountryCode(Integer merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
  }
  
  public SearchAttrList merchantPostalCode(String merchantPostalCode) {
    this.merchantPostalCode = merchantPostalCode;
    return this;
  }

  
  /**
  * Postal Code of the registered Merchant
  * @return merchantPostalCode
  **/
  @ApiModelProperty(required = true, value = "Postal Code of the registered Merchant")
  public String getMerchantPostalCode() {
    return merchantPostalCode;
  }
  public void setMerchantPostalCode(String merchantPostalCode) {
    this.merchantPostalCode = merchantPostalCode;
  }
  
  public SearchAttrList visaStoreId(Double visaStoreId) {
    this.visaStoreId = visaStoreId;
    return this;
  }

  
  /**
  * Unique identifier for a Branch/Outlet. Note: Optional when any one of MerchantName or VisaMerchantId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.
  * @return visaStoreId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier for a Branch/Outlet. Note: Optional when any one of MerchantName or VisaMerchantId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.")
  public Double getVisaStoreId() {
    return visaStoreId;
  }
  public void setVisaStoreId(Double visaStoreId) {
    this.visaStoreId = visaStoreId;
  }
  
  public SearchAttrList businessRegistrationId(String businessRegistrationId) {
    this.businessRegistrationId = businessRegistrationId;
    return this;
  }

  
  /**
  * Merchants Business Registration ID/Tax ID.Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or MerchantUrl or AcquirerCardAcceptorId is provided.
  * @return businessRegistrationId
  **/
  @ApiModelProperty(required = true, value = "Merchants Business Registration ID/Tax ID.Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or MerchantUrl or AcquirerCardAcceptorId is provided.")
  public String getBusinessRegistrationId() {
    return businessRegistrationId;
  }
  public void setBusinessRegistrationId(String businessRegistrationId) {
    this.businessRegistrationId = businessRegistrationId;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchAttrList searchAttrList = (SearchAttrList) o;
    return Objects.equals(this.merchantCity, searchAttrList.merchantCity) &&
        Objects.equals(this.merchantStreetAddress, searchAttrList.merchantStreetAddress) &&
        Objects.equals(this.merchantName, searchAttrList.merchantName) &&
        Objects.equals(this.merchantState, searchAttrList.merchantState) &&
        Objects.equals(this.visaMerchantId, searchAttrList.visaMerchantId) &&
        Objects.equals(this.acquiringBin, searchAttrList.acquiringBin) &&
        Objects.equals(this.merchantUrl, searchAttrList.merchantUrl) &&
        Objects.equals(this.merchantPhoneNumber, searchAttrList.merchantPhoneNumber) &&
        Objects.equals(this.acquirerCardAcceptorId, searchAttrList.acquirerCardAcceptorId) &&
        Objects.equals(this.merchantCountryCode, searchAttrList.merchantCountryCode) &&
        Objects.equals(this.merchantPostalCode, searchAttrList.merchantPostalCode) &&
        Objects.equals(this.visaStoreId, searchAttrList.visaStoreId) &&
        Objects.equals(this.businessRegistrationId, searchAttrList.businessRegistrationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantCity, merchantStreetAddress, merchantName, merchantState, visaMerchantId, acquiringBin, merchantUrl, merchantPhoneNumber, acquirerCardAcceptorId, merchantCountryCode, merchantPostalCode, visaStoreId, businessRegistrationId);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchAttrList {\n");
    
    sb.append("    merchantCity: ").append(toIndentedString(merchantCity)).append("\n");
    sb.append("    merchantStreetAddress: ").append(toIndentedString(merchantStreetAddress)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    merchantState: ").append(toIndentedString(merchantState)).append("\n");
    sb.append("    visaMerchantId: ").append(toIndentedString(visaMerchantId)).append("\n");
    sb.append("    acquiringBin: ").append(toIndentedString(acquiringBin)).append("\n");
    sb.append("    merchantUrl: ").append(toIndentedString(merchantUrl)).append("\n");
    sb.append("    merchantPhoneNumber: ").append(toIndentedString(merchantPhoneNumber)).append("\n");
    sb.append("    acquirerCardAcceptorId: ").append(toIndentedString(acquirerCardAcceptorId)).append("\n");
    sb.append("    merchantCountryCode: ").append(toIndentedString(merchantCountryCode)).append("\n");
    sb.append("    merchantPostalCode: ").append(toIndentedString(merchantPostalCode)).append("\n");
    sb.append("    visaStoreId: ").append(toIndentedString(visaStoreId)).append("\n");
    sb.append("    businessRegistrationId: ").append(toIndentedString(businessRegistrationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



