export const SELECT_BRAND = 'SELECT_BRAND';
export const GET_PRODUCTS_FOR_BRAND = 'GET_PRODUCTS_FOR_BRAND';
export const USER_LOGIN = 'USER_LOGIN';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const GET_MERCHANTS = 'GET_MERCHANTS';
export const FETCHED_MERCHANTS = 'FETCHED_MERCHANTS';
export const REQUEST_JOIN = 'REQUEST_JOIN';
export const JOINED_QUEUE = 'JOINED_QUEUE';
